### ISSUE TITLE
Group Role

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#17] opened 2016-03-07 17:52 UTC
The role cannot be added http://prntscr.com/acdck1

**Comment by emperorstarfinder** [comment] 2016-03-07 22:22
In order to ensure that you are not getting errors from bad configurations we recommend starting with a fresh setup.  This means fresh database, and completely fresh bin and untouched configuration files.  Please use the configurator via the consoles (Universe.Server.exe for grid and Universe.exe for regions).  The command here is run configurator.  This will ensure your configurations are clean and are not causing an error should one occur.

Our testing is unable to reproduce these issues.  Thus we recommend a fresh setup.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment] 2016-03-07 23:23
Сonfiguration as it was initially provided by you in the source files and the changes did not belong . I understand you do not have it because it does not use Windows, on Windows, the group will not work with almost 100 % of the functions work around 20 % and that of spruce and 10 server restart.

**Comment by emperorstarfinder** [comment] 2016-03-07 23:27
We actually do test on windows, Linux, and Mac OS X.

Can you send up a copy of the configuration files in a zip folder you can email them to me direct at emperor@secondgalaxy.com  that way we can see if theres something with those particular files.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment] 2016-03-07 23:59
Submitted

**Comment by emperorstarfinder** [comment] 2016-03-08 00:58
I will look at it after i eat dinner

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-03-08 02:13
Okay on preliminary review while this shouldn't matter to the viewer to much you should reverse these in Config/Grid/ServerConfiguration/GridInfoService.ini

From: 

;; long grid name: the long name of your grid
gridname = "ReaL Life"

;; short grid name: the short name of your grid
gridnick = "Real Life 3D"

To: 

;; long grid name: the long name of your grid
;; this is the name of your grid
gridname = "ReaL Life 3D"

;; short grid name: the short name of your grid
;; this is a shortened version of the grid name
;; for the viewers to use to distinguish your grid
gridnick = "RealLife"

**Comment by LifeGold** [comment] 2016-03-08 16:37
Unchanged still

**Comment by emperorstarfinder** [comment] 2016-03-08 17:38
Alright,

I will have to pull an ISO image for Windows Server 2012 then and test to see whats going in.  It is possible there is something going on in the server OS that would be a problem.  The Windows Server OS does not behave necessarily the same way as regular windows.

It will however be a couple hours before i can do this as i have to be at a meeting for work this afternoon.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment] 2016-03-08 21:42
I put the new server . That's what gives .

Mar 09 12:37:56 -  [LLClient View]: Caught exception while processing OpenMetaverse.Packets.MoneyBalanceRequestPacket for Mr ReaL_Life, Object reference not set to an instance of an object.    at Universe.Modules.Currency.BaseCurrencyServiceModule.SendMoneyBalance(IClientAPI client, UUID agentId, UUID sessionId, UUID transactionId) in c:\Users\Administrator\Desktop\Virtual-Universe-master\Universe\Modules\Currency\BaseCurrency\Base.CurrencyServices.cs:line 414
   at Universe.ClientStack.LLClientView.HandleMoneyBalanceRequest(IClientAPI sender, Packet Pack) in c:\Users\Administrator\Desktop\Virtual-Universe-master\Universe\ClientStack\LLClientView.cs:line 10416
   at Universe.ClientStack.LLClientView.ProcessSpecificPacketAsync(Object state) in c:\Users\Administrator\Desktop\Virtual-Universe-master\Universe\ClientStack\LLClientView.cs:line 729

Mar 09 12:38:08 -  [Base Http Server]: HandleRequest() threw System.NotImplementedException: The method or operation is not implemented.
   at Universe.Services.ProductInfoRequest.ProductInfoRequestCAP(String path, Stream request, OSHttpRequest httpRequest, OSHttpResponse httpResponse) in c:\Users\Administrator\Desktop\Virtual-Universe-master\Universe\Services\GenericServices\CapsService\CAPModules\ProductInfoRequestCAPS.cs:line 81
   at Universe.Framework.Servers.HttpServer.GenericStreamHandler.Handle(String path, Stream request, OSHttpRequest httpRequest, OSHttpResponse httpResponse) in c:\Users\Administrator\Desktop\Virtual-Universe-master\Universe\Framework\Servers\HttpServer\Http Methods\GenericStreamHandler.cs:line 51
   at Universe.Framework.Servers.HttpServer.BaseHttpServer.HandleRequest(HttpListenerContext context) in c:\Users\Administrator\Desktop\Virtual-Universe-master\Universe\Framework\Servers\HttpServer\BaseHttpServer.cs:line 385

**Comment by emperorstarfinder** [comment] 2016-03-08 22:28
As stated before the message about the ProductInfoRequestCap is not really an error.  This is just telling you that item is not yet implemented.  That error does not affect in any way the rest of the operations.  That is an error we are aware of.  ProductInfo is a new feature just recently implemented in SecondLife so it has not fully made its way to being fully implemented in most virtual world architectures as of yet.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by NoahStarfinder** [comment] 2016-03-08 22:48
This would be correct,

The error in the BaseCurrency is relating to the new
ProductInfoRequestCap() which is not fully implemented.  When I commit the
next batch of updates tonight I will suppress that message so it won't
cause confusion for folks.

That will get implemented shortly however.  Please remember ProductInfo()
features refer to the new Homes feature we are adding so thus this has not
yet been fully implemented.  This is coming apparently from Secondlife
which does have what they call Linden Homes for premium members.  It is
just getting implemented now by many virtual world architecture projects
that are open sourced.

-- 
Noah Starfinder
Core Developer
In-Galaxy Services and Features Developer
Grid Architecture Development Work Group Member
Second Galaxy Development Team

**Comment by LifeGold** [comment] 2016-03-09 00:12
Install the update that is now here

Mar 09 03:10:20 -  [LLCLIENTVIEW]: Caught exception while processing OpenMetaverse.Packets.MoneyBalanceRequestPacket for Mr ReaL_Life, Object reference not set to an instance of an object.    at Universe.Modules.Currency.BaseCurrencyServiceModule.SendMoneyBalance(IClientAPI client, UUID agentId, UUID sessionId, UUID transactionId) in c:\Users\Administrator\Desktop\Virtual-Universe-master\Universe\Modules\Currency\BaseCurrency\Base.CurrencyServices.cs:line 414
   at Universe.ClientStack.LLClientView.HandleMoneyBalanceRequest(IClientAPI sender, Packet Pack) in c:\Users\Administrator\Desktop\Virtual-Universe-master\Universe\ClientStack\LLClientView.cs:line 10422
   at Universe.ClientStack.LLClientView.ProcessSpecificPacketAsync(Object state) in c:\Users\Administrator\Desktop\Virtual-Universe-master\Universe\ClientStack\LLClientView.cs:line 730

Mar 09 03:10:23 -  [BASE HTTP SERVER]: HandleRequest() threw System.NotImplementedException: The method or operation is not implemented.
   at Universe.Services.ProductInfoRequest.ProductInfoRequestCAP(String path, Stream request, OSHttpRequest httpRequest, OSHttpResponse httpResponse) in c:\Users\Administrator\Desktop\Virtual-Universe-master\Universe\Services\GenericServices\CapsService\CAPModules\ProductInfoRequestCAPS.cs:line 81
   at Universe.Framework.Servers.HttpServer.GenericStreamHandler.Handle(String path, Stream request, OSHttpRequest httpRequest, OSHttpResponse httpResponse) in c:\Users\Administrator\Desktop\Virtual-Universe-master\Universe\Framework\Servers\HttpServer\Http Methods\GenericStreamHandler.cs:line 51
   at Universe.Framework.Servers.HttpServer.BaseHttpServer.HandleRequest(HttpListenerContext context) in c:\Users\Administrator\Desktop\Virtual-Universe-master\Universe\Framework\Servers\HttpServer\BaseHttpServer.cs:line 385

**Comment by NoahStarfinder** [comment] 2016-03-09 01:31
Not an error.  When you see that its not something to worry about.  I
didn't suppress that as we are working on that as we speak.


-- 
Noah Starfinder
Core Developer
In-Galaxy Services and Features Developer
Grid Architecture Development Work Group Member
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-03-10 00:59
For the error message relating to ProductInfo() in BaseCurrency please refer to Issue #18 

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-03-13 21:04
Closing as this error is known in Issue #18 so we do not get confused.

In addition a fix for the ProductInfo() error is being worked on.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Closed by emperorstarfinder** 2016-03-13 21:04 UTC
