### ISSUE TITLE
Error when creating an avatar

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#53] opened 2016-06-03 09:34 UTC
Error when creating an avatar http://prntscr.com/bbsmzn

Error when creating new region http://prntscr.com/bbslet

**Comment by emperorstarfinder** [comment] 2016-06-03 18:14
Unfortunately I am unable to reproduce this locally.  It is important that you answer the questions in the builtin template provided when opening an issue so we have an easier time understanding your configuration and problem. This way we are able to have better chances of reproducing the problem.

Are you running in grid mode? if so we do not recommend running grid mode using SQLite.  We recommend you run your grid using MySQL or MariaDB for your database service.

Are you using the latest copy of master with the updated configuration files? If not we encourage you to use the latest from the repository.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment] 2016-06-03 18:59
Work with this server which is now flooded. Use MySQL DBMS. Locations gives an Error when you already have created the region, trying new and create, but it is created but it is impossible to enter.
Google Перев

**Comment by emperorstarfinder** [comment] 2016-06-03 23:49
I would start with a fresh database (this means drop all current tables and let Virtual Universe recreate the tables) and a fresh copy of Virtual Universe (without all the files its backed up in the Data directory).  This should solve the problem.  If your not in production mode yet with your grid with users on the grid yet this is the best way.  

By doing this you will have to recreate accounts for any users but this will also ensure they will have all the correct info in the database as well.  

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment] 2016-06-04 12:30
After 15 minutes the server gave this error and no longer admits http://prntscr.com/bc89yv

**Comment by emperorstarfinder** [comment] 2016-06-04 14:12
You will probably want to reboot the host OS.  That should resolve the hang time for responses.  

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-06-16 14:58
Version 1.0.2 Release is now available with downloads in process of being added to main site.  You will want to start with a fresh copy.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-06-25 15:33
Closing as this appears to no longer be an issue and no further reporting of this issue by user.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Closed by emperorstarfinder** 2016-06-25 15:33 UTC
