### ISSUE TITLE
Bag

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#11] opened 2016-02-21 11:49 UTC
Good day. Found a bug you can put two things on the same place. http://prntscr.com/a62l8z

**Comment by emperorstarfinder** [comment] 2016-02-21 16:03
Hello there,

Can you please provide further information on how you accomplished this?  For example most viewers today have the ability to add attachment which will allow multiple attachments at the same attachment point.

More information will be needed to determine if there is a bug.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development Work Group Leader
Second Galaxy Development Team

**Comment by LifeGold** [comment] 2016-02-21 17:20
To write for a long time, and couldn't upload videos in YouTube. I had to fill in Vkontakte. Tried with two vieweres. The account tried a normal user. https://vk.com/videos343449267?section=recoms&z=video343449267_171918767

**Comment by emperorstarfinder** [comment] 2016-02-21 18:18
When you do this what messages is it showing on the console.  (some messages i.e. errors will only show up when the log level in the console is debug)?

Also can you provide us with what operating system the server is running on?

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development Work Group Leader
Second Galaxy Development Team

**Comment by LifeGold** [comment] 2016-02-21 18:50
In the console at the same time this is what happens . And if you restart the server , go to the game and one of the objects that you can not write append )
http://prntscr.com/a67rjs

**Comment by emperorstarfinder** [comment] 2016-02-21 18:58
Okay can you attach a copy of the text files for the logs for the Universe.Server.txt and Universe.txt  They can be found in the data directory.  This way i can see iwhat the servers are saying.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development Work Group Leader
Second Galaxy Development Team

**Comment by LifeGold** [comment] 2016-02-21 19:05
https://cloud.mail.ru/public/BmZB/AS7HhQcCV
https://cloud.mail.ru/public/F7pt/QJSckQ5hP

**Comment by emperorstarfinder** [comment] 2016-02-21 19:18
Thanks,

Reviewing the log you are getting Feb 21 10:02:50 -  [Local Asset Database] GetAsset(b95ea609-e7b5-5c26-3c12-b1932f1fba69) - Asset UUID was not found.

That message is normal behavior and is just letting you know that it cannot find an asset with that UUID in the database.  That is not actually a bug.  This is common when you upload objects such as mesh, OARS, and sometimes IARs because the assets will not have that particular UUID in the database as its a new asset.

As for the attachment issue I am not yet sure what would be causing that so I will need to do some digging to see if something is incorrect to cause this.  If your copying an object remember the parameters of the object you copied will exist in the new object so when creating an attachment it is usually best to create new objects.  

I will do some digging and see if i can pin down the attachments issue today 

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development Work Group Leader
Second Galaxy Development Team

**Comment by LifeGold** [comment] 2016-02-21 20:23
Thank you

**Comment by emperorstarfinder** [comment] 2016-02-21 20:38
Your very much welcome,

We also have an IRC support channel on Freenode #galaxyfutures you can find members of the Virtual-Universe and Second Galaxy Development Teams there as well 

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development Work Group Leader
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-02-21 21:08
Quick question here,

Are you selecting wear for both objects instead of right clicking the second object and selecting Add?

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development Work Group Leader
Second Galaxy Development Team

**Comment by LifeGold** [comment] 2016-02-21 21:53
Just 2 times the left mouse button click on the second object , and it is worn on the arm as the first

**Comment by emperorstarfinder** [comment] 2016-02-21 22:03
Okay,  I was just making sure as we are pretty sure what the problem is.  Just a matter of correction the implementation :)  Should be done in a day or two

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development Work Group Leader
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-02-23 15:23
NOTE:

Okay after checking LifeGold's grid it appears we need to add a check to tell the viewer if something is already attached to an attachment point when using the 'wear' option.  The RezMultipleAttachmentsFromInv() is not yet apparently in libOMV.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development Work Group Leader
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-02-23 21:42
I have corrected this as it appears the work around for Viewer versions 2 and 3 is the offender here.  We will have to correct the Add feature which is intended to allow the resident to wear multiple attachments on the same attachment point.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development Work Group Leader
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-02-24 00:31
Closing as user reports this issue is resolved in IRC.  Correction of the Add feature is noted in the Development Team's TODO list.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development Work Group Leader
Second Galaxy Development Team

**Closed by emperorstarfinder** 2016-02-24 00:31 UTC
Labels: bug
