### ISSUE TITLE
Bag Group

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#13] opened 2016-02-26 21:30 UTC
Create a group , you go to your profile , open the group section and there appears infinite . This is the first bug. http://prntscr.com/a8cn6w 
If you go out and get in the game , then everything is fine .

**Comment by emperorstarfinder** [comment] 2016-02-27 02:15
Can you tell us which viewer you were using when you saw this?  I would prefer to try to duplicate this with the same viewer.  Also have you tried this with other viewers as well?

Emperor Starfinder
CEO/ Founder
Grid Architecture Development Work Group Leader
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-02-27 02:59
Did a little testing using Alchemy Viewer.

In Alchemy Viewer I am unable to reproduce this bug.  It is somewhat possible that it could just be a bug with your particular viewer, though I would admit that would seem to be a remote problem.  Recommend trying to do a grid restart and restart the host machine as sometimes this could cause problems.  Also if you are planning to run a grid it is recommended to run your grid and region servers on a linux server (Ubuntu, Debian, etc)

I will leave this open so other members of the development team can have a look to see if there is something going on that I am unable to reproduce.

Emperor Starfinder
CEO/ Founder
Grid Architecture Development Work Group Leader
Second Galaxy Development Team

**Comment by LifeGold** [comment] 2016-02-27 12:35
I checked on Alchemy Screenshots made in it, just tested in FireStorm, And tried radnich PC under different Windows operating systems.

**Comment by LifeGold** [comment] 2016-02-27 12:39
My server is VDS it is possible to install only Windows the Possibility to install Ubuntu, Debian, etc they do not have((

**Comment by emperorstarfinder** [comment] 2016-02-27 13:14
ok as far as the operating system, unfortunately that sounds like something you'll need to take up with the hosting company.  The grid servers do work on windows but I usually recommend running on linux as grids operate better on linux.  I tested the bug locally but can't reproduce it locally as it appears all groups appear to be working fine in the group profile in Alchemy and other viewers.  You could run Virtual Universe locally to see if you get the same error.  If all works properly on a local instance then that would mean there is something that has gone wrong with Virtual Universe on your Windows 2012 server.

I will continue testing however just to be sure there isn't something going on that shouldn't be.

Emperor Starfinder
CEO/ Founder
Grid Architecture Development Work Group Leader
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-03-03 21:23
Closing as user reports this issue no longer persists.

Emperor Starfinder
CEO/ Founder
Grid Architecture Development Work Group Leader
Second Galaxy Development Team

**Closed by emperorstarfinder** 2016-03-03 21:23 UTC
Labels: bug
