### ISSUE TITLE
World Map

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#37] opened 2016-03-27 08:42 UTC
http://prntscr.com/akl7sn

**Comment by emperorstarfinder** [comment] 2016-03-28 13:52
I have tested this and it appears to be working.  This may be related to a configuration setting.  But will look further tonight when I get home from meetings.

**Comment by emperorstarfinder** [comment] 2016-04-14 22:34
Updates to OARs and IARs coming within the next couple of days.  There are a few flags missing that we do not yet have.  This may be the cause of this issue.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-04-25 16:45
Updates to all J2KDecoder services complete.  This should now be fixed.  

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-04-28 16:37
Closing as there has been no further activity on this and it appears to be fixed in recent commits.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Closed by emperorstarfinder** 2016-04-28 16:37 UTC
Labels: question
