### ISSUE TITLE
Error Virtual Universe 1.0.2 RC1

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#14] opened 2016-03-03 07:31 UTC
Mar 03 10:29:31 -  Creating System Group 'Virtual Universe Maintenance'
Mar 03 10:29:31 -  [MySQL Data Loader] ExecuteNonQuery(INSERT INTO group_data (GroupID, Name, Charter, InsigniaID, FounderID, MembershipFee, OpenEnrollment, ShowInList, AllowPublish, MaturePublish, OwnerRoleID) VALUES( ?GroupID, ?Name, ?Charter, ?InsigniaID, ?FounderID, ?MembershipFee, ?OpenEnrollment, ?ShowInList, ?AllowPublish, ?MaturePublish, ?OwnerRoleID )), MySql.Data.MySqlClient.MySqlException (0x80004005): Duplicate entry 'dc7b21cd-3c89-fcaa-31c8-25f9ffd224cd' for key 'PRIMARY'
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at MySql.Data.MySqlClient.MySqlHelper.ExecuteNonQuery(MySqlConnection connection, String commandText, MySqlParameter[] commandParameters)
   at MySql.Data.MySqlClient.MySqlHelper.ExecuteNonQuery(String connectionString, String commandText, MySqlParameter[] parms)
   at Universe.DataManager.MySQL.MySQLDataLoader.ExecuteNonQuery(String connStr, String sql, Dictionary`2 parameters, Boolean spamConsole) in c:\Users\Administrator\Desktop\Virtual-Universe-master\Universe\DataManagerPlugins\MySQL\MySQLDataManager.cs:line 140
Mar 03 10:29:31 -  [MySQL Data Loader] ExecuteNonQuery(INSERT INTO group_roles (GroupID, RoleID, Name, Description, Title, Powers) VALUES( ?GroupID, ?RoleID, ?Name, ?Description, ?Title, ?Powers )), MySql.Data.MySqlClient.MySqlException (0x80004005): Duplicate entry 'dc7b21cd-3c89-fcaa-31c8-25f9ffd224cd-00000000-0000-0000-0000-000' for key 'PRIMARY'
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at MySql.Data.MySqlClient.MySqlHelper.ExecuteNonQuery(MySqlConnection connection, String commandText, MySqlParameter[] commandParameters)
   at MySql.Data.MySqlClient.MySqlHelper.ExecuteNonQuery(String connectionString, String commandText, MySqlParameter[] parms)
   at Universe.DataManager.MySQL.MySQLDataLoader.ExecuteNonQuery(String connStr, String sql, Dictionary`2 parameters, Boolean spamConsole) in c:\Users\Administrator\Desktop\Virtual-Universe-master\Universe\DataManagerPlugins\MySQL\MySQLDataManager.cs:line 140
Mar 03 10:29:31 -  [AGM]: Agent bbb55499-7938-4752-ab7c-f7136e36cced is already in dc7b21cd-3c89-fcaa-31c8-25f9ffd224cd

**Comment by emperorstarfinder** [comment] 2016-03-03 14:32
This means generally that the user trying to join a group is already in that group and thus the database is treating it as a duplicate.  The evidence of this is at: Mar 03 10:29:31 - [AGM]: Agent bbb55499-7938-4752-ab7c-f7136e36cced is already in dc7b21cd-3c89-fcaa-31c8-25f9ffd224cd

That message says the agent or user (bbb55499-7938-4752-ab7c-f7136e36cced) is already in group (dc7b21cd-3c89-fcaa-31c8-25f9ffd224cd)

I also tested this on a fresh database with no errors.  You may need to start your beta grid with a fresh database.

Emperor Starfinder
CEO/ Core Founder
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment] 2016-03-03 18:59
It is strange that issues in version 1.0.0 of this error is not present.

**Comment by emperorstarfinder** [comment] 2016-03-03 19:05
It isn't an actual error.  The message just is MySQL telling the grid server that "hey wait a second here that person is already in this group".  If someone tries to join a group they are already in your likely to get that message.

I have tested this myself and have found no actual error and also tested on a fresh database as well so I will leave this open.  If this becomes persistent the logs for each case will help also you can set your consoles to the debug level by using the command set log level debug.  That way if there is an actual error we can try to pin it down but it would appear that the individual was just trying to join a group they are already in.

Emperor Starfinder
CEO/ Core Founder
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment] 2016-03-03 20:35
Thanks for the explanation

**Comment by emperorstarfinder** [comment] 2016-03-03 21:19
Your welcome,

It is good to hear the repeating groups in the user's profile has ceased.  That could just have been to a hiccup somewhere in the server or even the operating system.  Sometimes some unforseen issue will crop up that we cannot anticipate due to individual configurations such as operating systems, etc.

Emperor Starfinder
CEO/ Core Founder
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment] 2016-03-09 00:09
Removed database server put down to the new latest updates still this error

**Comment by NoahStarfinder** [comment] 2016-03-09 01:41
Are you sure someone isn't trying to join a group they already are part of?

This error generally means that someone is trying to join a group they are
already part of.

The recommended way of determining if this is an actual error or if it is
just someone attempting to join a group they are already in would be to
create a new user and have them try to join a group you have set up for
open enrollment.


-- 
Noah Starfinder
Core Developer
In-Galaxy Services and Features Developer
Grid Architecture Development Work Group Member
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-03-13 21:00
Closing as it appears this error no longer is an issue and is not able to be reproduced by development team members.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Closed by emperorstarfinder** 2016-03-13 21:00 UTC
Labels: question
