### ISSUE TITLE
LandObject error

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#23] opened 2016-03-16 18:04 UTC
[BUG] in Primerka: System.NullReferenceException: Object reference not set to an instance of an object
  at Universe.Modules.Land.LandObject+<SendLandUpdateToAvatarsOverMe>c__AnonStorey2.<>m__0 (IScenePresence avatar) <0x41cf94a0 + 0x0003c> in <filename unknown>:0 
  at Universe.Region.SceneGraph.ForEachScenePresence (System.Action`1 action) <0x418964b0 + 0x000f4> in <filename unknown>:0 
Март 17 02:58:50 - [BUG] Stack Trace:   at Universe.Modules.Land.LandObject+<SendLandUpdateToAvatarsOverMe>c__AnonStorey2.<>m__0 (IScenePresence avatar) <0x41cf94a0 + 0x0003c> in <filename unknown>:0 
  at Universe.Region.SceneGraph.ForEachScenePresence (System.Action`1 action) <0x418964b0 + 0x000f4> in <filename unknown>:0

**Comment by emperorstarfinder** [comment] 2016-03-16 18:37
your going to have to provide the entire error message it gave you that looks to only be part of it and follow the questions in the template provided when opening issues this way we know what exactly your doing so we can see whats going on and reproduce it ourselves.  thats what that template is for now.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment] 2016-03-16 18:51
With this problem as I saw it in the console , a server Beta - test , and there are about 22 people walking . But I try to learn from those who have been in the region that they did .

**Comment by emperorstarfinder** [comment] 2016-03-16 20:13
Okay any info you are able to give us as to what is causing this will be helpful.  

When opening a new issue you will see a template with questions relating to the issue.  Please use those questions to help describe the issue so we have that information when trying to reproduce and fix the problem.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-03-17 01:14
This issue is probably now resolved with the latest commit relating to CAPS

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-03-22 16:09
It would appear this might be something with ODE physics.  I will test on Bulletsim to see if this occurs as I actually unwittingly reproduced this error when I attempted to put a building out someone accidentally took and returned to me last night.  At least now we can confirm this is an actual bug we need to sort out.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-03-22 20:45
Can you explain more what you did when this occurred?  For example was a building or prims taken back to inventory and re-rezed?  and you were using OpenDynamicsEngine I assume.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-03-30 16:55
After further testing I recommend you change the physics engine your using to Bulletsim and see if the issues here persist.  This may be related to an issue with ODE

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-04-14 22:33
Updates to OARs and IARs coming within the next couple of days.  There are a few flags missing that we do not yet have.  This may be the cause of this issue.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-04-25 16:44
Updates to all archiver services complete.  This should now be fixed.  

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-04-28 16:35
Closing as nothing further has been reported on this and it appears to have been fixed in recent commits.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Closed by emperorstarfinder** 2016-04-28 16:35 UTC
Labels: bug, Needs Immediate Fix
