### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#16] opened 2016-03-05 17:51 UTC
Several times per minute produces errors like this do not tell me what it is?
 [Base Http Server]: HandleRequest() threw System.Net.HttpListenerException (0x80004005): An operation was attempted on a nonexistent network connection
   at System.Net.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at Universe.Framework.Servers.HttpServer.HttpServerHandlerHelpers.ReadString(Stream stream) in c:\Virtual-Universe-master\Universe\Framework\Servers\HttpServer\Http Methods\GenericStreamHandler.cs:line 103
   at Universe.Framework.Services.ServerHandler.Handle(String path, Stream requestData, OSHttpRequest httpRequest, OSHttpResponse httpResponse) in c:\Virtual-Universe-master\Universe\Framework\Services\ConnectorBase.cs:line 395
   at Universe.Framework.Servers.HttpServer.BaseHttpServer.HandleRequest(HttpListenerContext context) in c:\Virtual-Universe-master\Universe\Framework\Servers\HttpServer\BaseHttpServer.cs:line 385

**Comment by emperorstarfinder** [comment] 2016-03-05 17:59
That usually means a networking error but that particular error is not one we often see or have anyone reporting.  We will have to take a look at what is happening there.  When these errors show up and persist what is being done in-world?

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment] 2016-03-05 18:02
In the world nothing is done, generally anyone on the server when loading the map basically gives them away.

**Comment by emperorstarfinder** [comment] 2016-03-05 18:08
It sounds like a networking problem or possibly a configuration is off.  Are they trying to load the world map in-world or via the built in webui?



Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment] 2016-03-05 19:00
Where do you see tell me, I don't know how you configured the vu 1.0.1 RC1

**Comment by emperorstarfinder** [comment] 2016-03-05 19:23
All the configuration files are in the Config directory

Grid: Config/Grid/ServerConfiguration/
Region: Config/Sim/

The configuration directories have not really changed in Virtual Universe 1.0.2 RC1 except that we have moved the configuration files for individual servers (assuming you are running one server like Inventory on one machine and Asset server on another machine)

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by greythane** [comment] 2016-03-05 23:19
This appears to be an error caused by trying to access a handler that does not exist.
It may be caused by an configuration error or possibly by an external process sending a call with an incorrect format.
I would be looking initially for a configuration error that has modified a service handler or port.

**Comment by emperorstarfinder** [comment] 2016-03-05 23:48
That was what i was thinking initially as well.  he says its happening with the world map apparently but i haven't seen anything to suggest an exact error on console

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-03-06 02:40
i have gone through the configuration files,  there are some things we will need to clean up to make them uniform but all the key pieces and connectors are named correctly thus this is likely as has been said before to just be a matter of a port not open or a configuration that needs to be corrected.  

Remember on windows you must open the ports for both incoming and outgoing on TCP and UDP in order for things to work properly.  Some hosting providers may require ports to be added to their firewalls as well but usually that isn't an issue.

The ports required to be opened in the windows firewall (and router/ modem firewall) are:

Incoming
TCP: 8000-8999 (Note: the actual ports are 8000-8013 however the entire range is what I use)
UDP: 8000-8999 (Note above)
TCP: 9000-9999 (These ports are for the region server and the various regions)
UDP: 9000-9999 (Note above)

Outgoing
Note: Be sure you tick the box to allow the connection
TCP: 8000-8999 (Note: the actual ports are 8000-8013 however the entire range is what I use)
UDP: 8000-8999 (Note above)
TCP: 9000-9999 (These ports are for the region server and the various regions)
UDP: 9000-9999 (Note above)

Keeping open for Noah to look and determine if there is something more going on that we don't know about.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment] 2016-03-07 17:48
New Error 

[Base Http Server]: HandleRequest() threw System.NotImplementedException: The method or operation is not implemented.
   at Universe.Services.ProductInfoRequest.ProductInfoRequestCAP(String path, Stream request, OSHttpRequest httpRequest, OSHttpResponse httpResponse) in c:\Users\Administrator\Desktop\Virtual-Universe-master\Universe\Services\GenericServices\CapsService\CAPModules\ProductInfoRequestCAPS.cs:line 81
   at Universe.Framework.Servers.HttpServer.GenericStreamHandler.Handle(String path, Stream request, OSHttpRequest httpRequest, OSHttpResponse httpResponse) in c:\Users\Administrator\Desktop\Virtual-Universe-master\Universe\Framework\Servers\HttpServer\Http Methods\GenericStreamHandler.cs:line 51
   at Universe.Framework.Servers.HttpServer.BaseHttpServer.HandleRequest(HttpListenerContext context) in c:\Users\Administrator\Desktop\Virtual-Universe-master\Universe\Framework\Servers\HttpServer\BaseHttpServer.cs:line 385

**Comment by emperorstarfinder** [comment] 2016-03-07 17:51
Thats not a bug its just saying that the new ProductInfoRequest stuff is not yet implemented.  It will not impact any functionality in-world for anyone.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment] 2016-03-07 17:53
How about this one?

[LLClient View]: Caught exception while processing OpenMetaverse.Packets.GroupAccountSummaryRequestPacket for Mr ReaL_Life, Object reference not set to an instance of an object.    at Universe.Modules.Currency.BaseCurrencyServiceModule.Balance(UUID agentID) in c:\Users\Administrator\Desktop\Virtual-Universe-master\Universe\Modules\Currency\BaseCurrency\Base.CurrencyServices.cs:line 221
   at Universe.Modules.Avatar.Groups.GroupMoneyModule.client_OnGroupAccountSummaryRequest(IClientAPI client, UUID agentID, UUID groupID, UUID requestID, Int32 currentInterval, Int32 intervalDays) in c:\Users\Administrator\Desktop\Virtual-Universe-master\Universe\Modules\Avatar\Groups\GroupMoneyModule.cs:line 181
   at Universe.ClientStack.LLClientView.HandleGroupAccountSummaryRequest(IClientAPI client, Packet Packet) in c:\Users\Administrator\Desktop\Virtual-Universe-master\Universe\ClientStack\LLClientView.cs:line 11270
   at Universe.ClientStack.LLClientView.ProcessSpecificPacketAsync(Object state) in c:\Users\Administrator\Desktop\Virtual-Universe-master\Universe\ClientStack\LLClientView.cs:line 729

**Comment by emperorstarfinder** [comment] 2016-03-07 18:06
Moved the error for BaseCurrency to Issue #18 so we can look into it as the GroupAccount features may not yet be fully implemented in libOMV yet.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-03-13 20:59
Closing as the error relating to ProductInfo() is in its own issue now and the error originally posted in this issue appears to no longer be an issue.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Closed by emperorstarfinder** 2016-03-13 20:59 UTC
Labels: question
