### ISSUE TITLE
Error when loading OAR

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#50] opened 2016-05-14 23:28 UTC
When loading the Oar http://prntscr.com/b44qet

**Comment by BriaKallistaStarfinder** [comment] 2016-05-15 03:22
Aloha,

I have confirmed this and am passing it to the appropriate core developer for further resolution.

Also in the future please use the built in template when reporting an issue and answer the questions provided.  And please be more specific in the title as to what the issue is so we wont be confused with what issue we are referring to when responding.

Thanks

Briakallista Starfinder
Core Developer
In-Galaxy Roleplay Lifestyles Developer
Work Group member
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment] 2016-05-17 00:56
Good time of day. Do not tell me when to expect the elimination of this error, cant any one upload location(

**Comment by emperorstarfinder** [comment] 2016-05-17 01:05
We are working on this issue as we speak.  It will take some debugging and testing to figure out what the actual cause is relating to this.  Should have a fix to this shortly.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-05-17 11:56
Good morning,

After further review, it appears the archiver is not able to get any script module for the scene.  This would in fact cause the error you have seen and which has been reproduced by members of our team.  We are looking into this further and will have this fixed shortly.  Upon a fix passing our internal tests it will arrive in the master branch.  

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-05-18 13:03
Commit: e54f3a797ab02a34db99364f3a8bb18027c061d3 should resolve this.  Good catch @greythane I will make sure the downloadable versions on http://virtual-planets.org/downloads/ are updated with this fix as well.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2016-05-19 19:17
Closing as this is now resolved.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Closed by emperorstarfinder** 2016-05-19 19:17 UTC
Labels: bug, Bug Confirmed, Needs Immediate Fix
