### ISSUE TITLE
LLClient view

### ISSUE THREAD

**Issue by RyujinnJakka** [Virtual-Universe/Virtual-Universe#8] opened 2015-09-26 04:04 UTC
I beleave this messaged appeared after trying to force avatar update and rebake/bake the textures.

[LLCLIENTVIEW]: Caught exception while processing OpenMetaverse.Packets.RequestImagePacket for Ryujin Jakka, The specified itemm is not in the queue.   at Universe.Framework.Utilities.PriorityQueue`2[Universe.ClientStack.J2KImage,System.Single].Remove (Universe.ClientStack.J2KImage item, IEqualityComparer comparer) [0x00000] in <filename unknown>:0
  at Universe.Framework.Utilities.PriorityQueue`2[Universe.ClientStack.J2KImage,System.Single].Remove (Universe.ClientStack.J2KImage item) [0x00000] in <filename unknown>:0
  at Universe.ClientStack.LLImageManager.EnqueueReq (Universe.Framework.ClientInterfaces.TextureRequestArgs newRequest) [0x00000] in <filename unknown>:0
  at Universe.ClientStack.LLClientView.HandleRequestImage (IClientAPI sender, OpenMetaverse.Packets.Packet Pack) [0x00000] in <filename unknown>:0
  at Universe.ClientStack.LLClientView.ProcessSpecificPacketAsync (System.Object state) [0x00000] in <filename unknown>:0

**Comment by NoahStarfinder** [comment] 2015-09-26 13:37
This one looks to be intended to have been put in issue #6 

If you are using this on a local machine and its not a production grid please try starting it fresh.  This way we can rule out its not something that got changed from the previous region loading issue.as sometimes all it takes is a configuration change for this to get fouled up.  If that doesn't work let us know so we can have a look at what is going on.

Noah Starfinder
Core Developer
In-Galaxy Services & Features Developer
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment] 2015-10-20 21:52
Closed as indicated in issue #6

**Comment by emperorstarfinder** [comment] 2015-11-14 08:23
Reopening this issue as I have reproduced this.

Emperor Starfinder
Core Developer
CEO
Grid Architecture Development
Second Galaxy Development Team

**Closed** 2015-11-26 00:40 UTC
